### ISSUE TITLE
Map - only set view once

### ISSUE THREAD

**Issue by davidmjiang** [ContactAssistApp/dashboard#39]
Right now, the map tries to set view for every card, which makes the map flicker quickly. We should only set the view once.

**Comment by wangmeng255** [comment]
Hi David, I don't quite "the map tries to set view for every card". Can we discuss this offline? Thanks

**Comment by davidmjiang** [comment]
@wangmeng255 If you look in Map.jsx, you'll see we loop over every card and add it to the map. When we draw on the map, it seems it is trying to center the map on the card with map.setView(). Feel free to ping me too if you have more questions. Thanks!
![image](https://user-images.githubusercontent.com/16966368/90578446-2d445700-e178-11ea-9f42-89eace5c092f.png)
